# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pissuser',
            name='token',
            field=models.CharField(default='', max_length=64, unique=True),
        ),
    ]
