# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20161222_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pissactivecode',
            name='used_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
