# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20161222_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pissuser',
            name='created_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
