# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_auto_20161227_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='pissuser',
            name='last_login_ip',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='pissuser',
            name='last_login_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='pissuser',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pissuser',
            name='status',
            field=models.PositiveSmallIntegerField(default=9001),
        ),
        migrations.AlterField(
            model_name='pissuserextra',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pissuserextra',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
