# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_auto_20161227_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='pissuserextra',
            name='bucket_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
