# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PissImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, default=None)),
                ('user_id', models.BigIntegerField()),
                ('qiniu_url', models.CharField(max_length=512)),
                ('piss_url', models.CharField(max_length=32, unique=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'piss_images',
            },
        ),
    ]
