# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pissimages',
            name='local_filename',
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
    ]
