# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine_app', '0003_pissimages_qiniu_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pissimages',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
